apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    run: jupyter
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    run: jupyter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: jupyter
    spec:
      containers:
      - name: jupyter
        image: 240980109537.dkr.ecr.us-east-1.amazonaws.com/jupyter:latest
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: notebook
          mountPath: /notebook
        #securityContext:
        #  privileged: true
        #  runAsUser: 0
      volumes:
      - name: notebook
        awsElasticBlockStore:
          volumeID: vol-0cf68d07c01618b60 # Must already exist.
          fsType: ext4
