apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:240980109537:certificate/da3b47a7-8bd1-4deb-8c43-885e19acfcdb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 80
    protocol: TCP
    name: https
  selector:
    run: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: nginx-frontend
        # NOTE: Don't use the :latest tag in production. see http://kubernetes.io/docs/user-guide/config-best-practices/#container-images
        image: 240980109537.dkr.ecr.us-east-1.amazonaws.com/nginx-frontend:latest
        ports:
        - containerPort: 80
      - name: frontend
        image: 240980109537.dkr.ecr.us-east-1.amazonaws.com/frontend:dev
        ports:
        - containerPort: 5000

