# https://chrome.google.com/webstore/developer/edit/ofdkhkelcafdphpddfobhbbblgnloian
crxId: 'ofdkhkelcafdphpddfobhbbblgnloian'
crxUrl: 'https://chrome.google.com/webstore/detail/ofdkhkelcafdphpddfobhbbblgnloian'
