#
# Test node server.
#

version: '2'

services:

  #
  # nginx
  # https://github.com/jwilder/nginx-proxy
  #

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always

    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  #
  # Test Server
  # Access via http://dockerhost.net (via /etc/hosts)
  # docker exec -it node-server /bin/bash
  #

  node-server:
    build: .
    container_name: node-server
    restart: always

    # NOTE: Not required if just accessing via nginx.
    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=dockerhost.net
