#
# Test node server.
#

version: '2'

services:

  #
  # After editing Dockerfile:
  # > docker-compose build
  #
  # After editing docker-compose.yml (NOTE: docker-compose up DOES NOT restart containers).
  # > docker-compose up --force-recreate --remove-orphans
  #

  #
  # nginx
  # https://github.com/jwilder/nginx-proxy
  # docker exec -it nginx-proxy /bin/bash
  # more /etc/nginx/nginx.conf
  #

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always

    links:
      - node-server

    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  #
  # Test Server
  # Access via http://dockerhost.net (via /etc/hosts)
  # docker exec -it node-server /bin/bash
  #

  node-server:
    build: .
    container_name: node-server
    restart: always

    # NOTE: Not required if just accessing via nginx.
    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=production
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=dockerhost.net
