#
# Test node server.
#

version: '2'

services:

  #
  # nginx
  #

  nginx-proxy:
    image: jwilder/nginx-proxy

    links:
      - test-server:TEST_SERVER

    ports:
      - 80:80

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  #
  # Test Server
  # Access via http://dockerhost.net (via /etc/hosts)
  #

  test-server:
    build: .

    restart: always

    environment:
      - VIRTUAL_HOST=dockerhost.net

    ports:
      - '8080:8080'
