#
# Frontend Server.
#

PLATFORM:
  WEB:    'web'
  CRX:    'crx'
  MOBILE: 'mobile'

DOM_ROOT: 'app-root'

APP_PATH: '/app'

APP_NAME: 'minder'

# NOTE: Changed by grunt:version
APP_VERSION: "0.1.13"

# NOTE: Express lowercases headers.
# TODO(burdon): Move to minder-core.
HEADER:

  # Client ID set by server (Web) or on registration (CRX, mobile).
  CLIENT_ID: 'minder-client'

  # Use by Apollo network middleware to track request/response messages.
  REQUEST_ID: 'minder-request'

# https://chrome.google.com/webstore/developer/edit/ofdkhkelcafdphpddfobhbbblgnloian
CRX_ID: 'ofdkhkelcafdphpddfobhbbblgnloian'
CRX_URL: 'https://chrome.google.com/webstore/detail/ofdkhkelcafdphpddfobhbbblgnloian'
