# https://console.cloud.google.com/iam-admin/settings/project?project=minder-beta
projectNumber: 189079594739

# Created 11/28/16
# Web application credentials.
# https://console.developers.google.com/apis/credentials/oauthclient/189079594739-s67su4gkudu0058ub4lpcr3tnp3fslgj.apps.googleusercontent.com?project=minder-beta
clientId: '189079594739-s67su4gkudu0058ub4lpcr3tnp3fslgj.apps.googleusercontent.com'
clientSecret: 'WZypHT09Z8Fy8NHVKY3qmMFt'
