kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-research
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      volume: research
---
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-test
spec:
  containers:
    - name: ubuntu
      image: ubuntu:16.04
      command:
        - sleep
        - "3600"
      volumeMounts:
      - mountPath: "/home/research"
        name: home-research
  volumes:
    - name: home-research
      persistentVolumeClaim:
        claimName: pvc-research
