apiVersion: batch/v1
kind: Job
metadata:
  name: exp-58b326e86a78700052dc5331
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        run: exp-58b326e86a78700052dc5331
    spec:
      restartPolicy: OnFailure
      containers:
      - name: trainer
        image: minderlabs/jupyter:madadam
        #image: 240980109537.dkr.ecr.us-east-1.amazonaws.com/jupyter:madadam
        #imagePullPolicy: Always
        env:
          - name: EXPERIMENT_ID
            value: "58b326e86a78700052dc5331" # FIXME
